version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: app/backend/Dockerfile
    container_name: flask_api
    ports:
      - "5000:5000"
    volumes:
      - ./app/backend/requirements.txt:/app/requirements.txt
    environment:
      - FLASK_APP=src/main.py
      - FLASK_ENV=development
      - FLASK_RUN_HOST=0.0.0.0
    command: flask run
